/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsList: typeof import('./components/ActionsList/index.tsx')['default']
    AlertView: typeof import('./components/AlertView/index.tsx')['default']
    ApiTable: typeof import('./components/Table/ApiTable.tsx')['default']
    Button: typeof import('./components/Button/index.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.tsx')['default']
    DataTable: typeof import('./components/Table/DataTable.tsx')['default']
    DetailsFieldsDialog: typeof import('./components/detailsFieldsDialog/index.tsx')['default']
    Field: typeof import('./components/Field/index.tsx')['default']
    FieldsSections: typeof import('./components/FieldsSections/index.tsx')['default']
    FileInput: typeof import('./components/FileInput/index.vue')['default']
    HeaderFooter: typeof import('./components/Table/HeaderFooter.tsx')['default']
    Icon: typeof import('./components/Icon/index.vue')['default']
    PageHeader: typeof import('./components/PageHeader/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./components/SnackBar/SnackBar.vue')['default']
    Table: typeof import('./components/Table/Table.tsx')['default']
    TableRowActions: typeof import('./components/Table/TableRowActions.tsx')['default']
    TextField: typeof import('./components/TextField/index.vue')['default']
    ThemedText: typeof import('./components/ThemedText/index.tsx')['default']
    ThemedView: typeof import('./components/ThemedView/index.tsx')['default']
  }
}

// For TSX support
declare global {
  const ActionsList: typeof import('./components/ActionsList/index.tsx')['default']
  const AlertView: typeof import('./components/AlertView/index.tsx')['default']
  const ApiTable: typeof import('./components/Table/ApiTable.tsx')['default']
  const Button: typeof import('./components/Button/index.vue')['default']
  const ConfirmDialog: typeof import('./components/ConfirmDialog.tsx')['default']
  const DataTable: typeof import('./components/Table/DataTable.tsx')['default']
  const DetailsFieldsDialog: typeof import('./components/detailsFieldsDialog/index.tsx')['default']
  const Field: typeof import('./components/Field/index.tsx')['default']
  const FieldsSections: typeof import('./components/FieldsSections/index.tsx')['default']
  const FileInput: typeof import('./components/FileInput/index.vue')['default']
  const HeaderFooter: typeof import('./components/Table/HeaderFooter.tsx')['default']
  const Icon: typeof import('./components/Icon/index.vue')['default']
  const PageHeader: typeof import('./components/PageHeader/index.tsx')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SnackBar: typeof import('./components/SnackBar/SnackBar.vue')['default']
  const Table: typeof import('./components/Table/Table.tsx')['default']
  const TableRowActions: typeof import('./components/Table/TableRowActions.tsx')['default']
  const TextField: typeof import('./components/TextField/index.vue')['default']
  const ThemedText: typeof import('./components/ThemedText/index.tsx')['default']
  const ThemedView: typeof import('./components/ThemedView/index.tsx')['default']
}